import dotenv from "dotenv";
import mongoose from "mongoose";
import Car from "./src/models/car.model.js";
import connectDB from "./src/config/db.js";

dotenv.config();

const sampleCars = [
  {
    "make": "Volkswagen",
    "model": "Polo",
    "year": 2019,
    "mileage_city": 17.0,
    "mileage_highway": 22.7,
    "seating_capacity": 4,
    "price": 1272125,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 55,
    "engine": "1307cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Mahindra",
    "model": "Thar",
    "year": 2023,
    "mileage_city": 19.8,
    "mileage_highway": 23.4,
    "seating_capacity": 7,
    "price": 1319305,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 58,
    "engine": "1097cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "BMW",
    "model": "X5",
    "year": 2024,
    "mileage_city": 10.2,
    "mileage_highway": 22.0,
    "seating_capacity": 7,
    "price": 1044682,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 48,
    "engine": "2283cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Kia",
    "model": "Seltos",
    "year": 2021,
    "mileage_city": 11.4,
    "mileage_highway": 15.5,
    "seating_capacity": 5,
    "price": 2034602,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 54,
    "engine": "1494cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Mercedes",
    "model": "E-Class",
    "year": 2022,
    "mileage_city": 10.2,
    "mileage_highway": 19.2,
    "seating_capacity": 7,
    "price": 1617771,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 47,
    "engine": "1860cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Toyota",
    "model": "RAV4",
    "year": 2022,
    "mileage_city": 16.8,
    "mileage_highway": 18.6,
    "seating_capacity": 6,
    "price": 1630110,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 52,
    "engine": "1727cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Hyundai",
    "model": "Verna",
    "year": 2019,
    "mileage_city": 13.0,
    "mileage_highway": 24.4,
    "seating_capacity": 4,
    "price": 1220544,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 39,
    "engine": "1116cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Toyota",
    "model": "RAV4",
    "year": 2022,
    "mileage_city": 13.3,
    "mileage_highway": 24.8,
    "seating_capacity": 4,
    "price": 1491715,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 45,
    "engine": "2981cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Volkswagen",
    "model": "Taigun",
    "year": 2021,
    "mileage_city": 13.1,
    "mileage_highway": 18.4,
    "seating_capacity": 5,
    "price": 990655,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 57,
    "engine": "2436cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Hyundai",
    "model": "Verna",
    "year": 2021,
    "mileage_city": 12.8,
    "mileage_highway": 20.4,
    "seating_capacity": 6,
    "price": 1659689,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 58,
    "engine": "1321cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Volkswagen",
    "model": "Vento",
    "year": 2021,
    "mileage_city": 14.7,
    "mileage_highway": 19.7,
    "seating_capacity": 4,
    "price": 819733,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 58,
    "engine": "1197cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "BMW",
    "model": "X5",
    "year": 2023,
    "mileage_city": 17.2,
    "mileage_highway": 21.7,
    "seating_capacity": 5,
    "price": 1076517,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 43,
    "engine": "1148cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Hyundai",
    "model": "Creta",
    "year": 2023,
    "mileage_city": 12.0,
    "mileage_highway": 16.2,
    "seating_capacity": 4,
    "price": 1279896,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 49,
    "engine": "2538cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Honda",
    "model": "Civic",
    "year": 2020,
    "mileage_city": 14.6,
    "mileage_highway": 15.5,
    "seating_capacity": 5,
    "price": 1657257,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 49,
    "engine": "2861cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Hyundai",
    "model": "i20",
    "year": 2019,
    "mileage_city": 10.2,
    "mileage_highway": 18.6,
    "seating_capacity": 4,
    "price": 2378239,
    "fuel_type": "Diesel",
    "transmission": "Manual",
    "fuel_tank_capacity": 37,
    "engine": "2670cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Kia",
    "model": "Seltos",
    "year": 2024,
    "mileage_city": 16.9,
    "mileage_highway": 17.3,
    "seating_capacity": 7,
    "price": 2399803,
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "fuel_tank_capacity": 51,
    "engine": "2925cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Audi",
    "model": "Q7",
    "year": 2019,
    "mileage_city": 14.2,
    "mileage_highway": 24.4,
    "seating_capacity": 7,
    "price": 742139,
    "fuel_type": "Diesel",
    "transmission": "Manual",
    "fuel_tank_capacity": 58,
    "engine": "1458cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Honda",
    "model": "Accord",
    "year": 2019,
    "mileage_city": 14.7,
    "mileage_highway": 18.6,
    "seating_capacity": 4,
    "price": 2453273,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 51,
    "engine": "2334cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Mahindra",
    "model": "XUV700",
    "year": 2020,
    "mileage_city": 10.8,
    "mileage_highway": 17.9,
    "seating_capacity": 4,
    "price": 2278256,
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "fuel_tank_capacity": 45,
    "engine": "2048cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "Audi",
    "model": "Q7",
    "year": 2019,
    "mileage_city": 16.5,
    "mileage_highway": 15.4,
    "seating_capacity": 7,
    "price": 1482195,
    "fuel_type": "Electric",
    "transmission": "Manual",
    "fuel_tank_capacity": 56,
    "engine": "2774cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Audi",
    "model": "A4",
    "year": 2022,
    "mileage_city": 19.0,
    "mileage_highway": 23.7,
    "seating_capacity": 6,
    "price": 2378659,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 57,
    "engine": "1354cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Toyota",
    "model": "RAV4",
    "year": 2023,
    "mileage_city": 16.6,
    "mileage_highway": 17.2,
    "seating_capacity": 4,
    "price": 1018779,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 50,
    "engine": "1655cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Toyota",
    "model": "Corolla",
    "year": 2022,
    "mileage_city": 17.5,
    "mileage_highway": 24.8,
    "seating_capacity": 4,
    "price": 1896473,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 38,
    "engine": "2344cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "BMW",
    "model": "5 Series",
    "year": 2020,
    "mileage_city": 19.0,
    "mileage_highway": 18.4,
    "seating_capacity": 5,
    "price": 749905,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 59,
    "engine": "1173cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Mercedes",
    "model": "GLA",
    "year": 2023,
    "mileage_city": 19.4,
    "mileage_highway": 18.1,
    "seating_capacity": 4,
    "price": 999781,
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "fuel_tank_capacity": 59,
    "engine": "1132cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Hyundai",
    "model": "Creta",
    "year": 2022,
    "mileage_city": 13.0,
    "mileage_highway": 23.0,
    "seating_capacity": 5,
    "price": 2140580,
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "fuel_tank_capacity": 49,
    "engine": "2621cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "BMW",
    "model": "5 Series",
    "year": 2020,
    "mileage_city": 17.4,
    "mileage_highway": 18.5,
    "seating_capacity": 4,
    "price": 2110264,
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "fuel_tank_capacity": 55,
    "engine": "1022cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "Hyundai",
    "model": "Creta",
    "year": 2021,
    "mileage_city": 19.0,
    "mileage_highway": 16.1,
    "seating_capacity": 6,
    "price": 867175,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 43,
    "engine": "2417cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Mahindra",
    "model": "Scorpio",
    "year": 2019,
    "mileage_city": 14.4,
    "mileage_highway": 22.0,
    "seating_capacity": 5,
    "price": 1077114,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 49,
    "engine": "1837cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Honda",
    "model": "Accord",
    "year": 2020,
    "mileage_city": 10.1,
    "mileage_highway": 18.4,
    "seating_capacity": 6,
    "price": 2483065,
    "fuel_type": "Diesel",
    "transmission": "Manual",
    "fuel_tank_capacity": 42,
    "engine": "1091cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Volkswagen",
    "model": "Vento",
    "year": 2020,
    "mileage_city": 13.0,
    "mileage_highway": 23.1,
    "seating_capacity": 7,
    "price": 1899297,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 51,
    "engine": "2004cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Honda",
    "model": "CR-V",
    "year": 2018,
    "mileage_city": 16.1,
    "mileage_highway": 22.6,
    "seating_capacity": 6,
    "price": 1434687,
    "fuel_type": "Diesel",
    "transmission": "Manual",
    "fuel_tank_capacity": 49,
    "engine": "1293cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Mercedes",
    "model": "C-Class",
    "year": 2024,
    "mileage_city": 17.0,
    "mileage_highway": 15.4,
    "seating_capacity": 5,
    "price": 824157,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 54,
    "engine": "1110cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "BMW",
    "model": "X5",
    "year": 2023,
    "mileage_city": 13.7,
    "mileage_highway": 19.8,
    "seating_capacity": 6,
    "price": 616459,
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "fuel_tank_capacity": 39,
    "engine": "2578cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "Kia",
    "model": "Sonet",
    "year": 2022,
    "mileage_city": 12.8,
    "mileage_highway": 20.2,
    "seating_capacity": 4,
    "price": 1217039,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 35,
    "engine": "2157cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "Audi",
    "model": "Q7",
    "year": 2021,
    "mileage_city": 10.1,
    "mileage_highway": 24.6,
    "seating_capacity": 4,
    "price": 1415858,
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "fuel_tank_capacity": 53,
    "engine": "2397cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Ford",
    "model": "Figo",
    "year": 2018,
    "mileage_city": 16.1,
    "mileage_highway": 19.9,
    "seating_capacity": 5,
    "price": 1754491,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 53,
    "engine": "1452cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Hyundai",
    "model": "i20",
    "year": 2022,
    "mileage_city": 15.6,
    "mileage_highway": 21.9,
    "seating_capacity": 6,
    "price": 739424,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 43,
    "engine": "1739cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "Volkswagen",
    "model": "Vento",
    "year": 2024,
    "mileage_city": 11.5,
    "mileage_highway": 16.5,
    "seating_capacity": 5,
    "price": 1487339,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 44,
    "engine": "2588cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Mahindra",
    "model": "Thar",
    "year": 2023,
    "mileage_city": 14.0,
    "mileage_highway": 18.4,
    "seating_capacity": 4,
    "price": 747617,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 59,
    "engine": "1576cc",
    "description": "A reliable and efficient car with excellent comfort."
  },
  {
    "make": "BMW",
    "model": "X5",
    "year": 2023,
    "mileage_city": 17.5,
    "mileage_highway": 19.5,
    "seating_capacity": 7,
    "price": 1097999,
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "fuel_tank_capacity": 38,
    "engine": "1581cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Mercedes",
    "model": "GLA",
    "year": 2018,
    "mileage_city": 11.0,
    "mileage_highway": 23.3,
    "seating_capacity": 5,
    "price": 1343762,
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "fuel_tank_capacity": 40,
    "engine": "2848cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Honda",
    "model": "Accord",
    "year": 2018,
    "mileage_city": 19.0,
    "mileage_highway": 19.1,
    "seating_capacity": 7,
    "price": 2181469,
    "fuel_type": "Electric",
    "transmission": "Manual",
    "fuel_tank_capacity": 45,
    "engine": "2834cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "BMW",
    "model": "X5",
    "year": 2022,
    "mileage_city": 17.5,
    "mileage_highway": 24.7,
    "seating_capacity": 7,
    "price": 1777513,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 45,
    "engine": "2651cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "Kia",
    "model": "Sonet",
    "year": 2021,
    "mileage_city": 12.2,
    "mileage_highway": 23.0,
    "seating_capacity": 7,
    "price": 2078152,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 39,
    "engine": "2420cc",
    "description": "Designed for the urban lifestyle with fuel efficiency."
  },
  {
    "make": "Volkswagen",
    "model": "Taigun",
    "year": 2018,
    "mileage_city": 12.9,
    "mileage_highway": 17.1,
    "seating_capacity": 7,
    "price": 1777425,
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "fuel_tank_capacity": 39,
    "engine": "1377cc",
    "description": "A premium driving experience with cutting-edge technology."
  },
  {
    "make": "Toyota",
    "model": "Camry",
    "year": 2021,
    "mileage_city": 11.5,
    "mileage_highway": 23.7,
    "seating_capacity": 7,
    "price": 878967,
    "fuel_type": "Diesel",
    "transmission": "Manual",
    "fuel_tank_capacity": 55,
    "engine": "2884cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Toyota",
    "model": "RAV4",
    "year": 2019,
    "mileage_city": 19.9,
    "mileage_highway": 21.9,
    "seating_capacity": 4,
    "price": 2182418,
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "fuel_tank_capacity": 48,
    "engine": "1936cc",
    "description": "Perfect blend of performance and style."
  },
  {
    "make": "Volkswagen",
    "model": "Polo",
    "year": 2018,
    "mileage_city": 19.7,
    "mileage_highway": 18.1,
    "seating_capacity": 4,
    "price": 1762578,
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "fuel_tank_capacity": 42,
    "engine": "1761cc",
    "description": "Spacious, modern, and equipped with advanced features."
  },
  {
    "make": "Ford",
    "model": "Figo",
    "year": 2024,
    "mileage_city": 10.0,
    "mileage_highway": 23.7,
    "seating_capacity": 7,
    "price": 2155127,
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "fuel_tank_capacity": 45,
    "engine": "1452cc",
    "description": "A premium driving experience with cutting-edge technology."
  }
];

const seedCars = async () => {
  await connectDB();
  try {
    await Car.deleteMany();
    await Car.insertMany(sampleCars);
    console.log("Seed data inserted!");
    process.exit();
  } catch (err) {
    console.error("Failed to insert seed data", err);
    process.exit(1);
  }
};

seedCars();
